### ISSUE TITLE
window Installation failed

### ISSUE THREAD

**Issue by Liting1** [song940/node-bluetooth#56]
![屏幕截图 2021-09-02 212157](https://user-images.githubusercontent.com/33544236/131851207-e87d3de1-bdd9-4f93-9575-aa758563d380.png)

**Comment by drizzt00s** [comment]
same problem, how to fix this?

**Comment by drizzt00s** [comment]
can this be used on windows or it cannot be?

**Comment by thefakhreddin** [comment]
@drizzt00s 
I've encountered this problem many times for installing different packages. It's primarily has something to do with the python and visual studio C++ developing package. Following the instructions on [node-gyp](https://www.npmjs.com/package/node-gyp) docs must do the job but since this package hasn't been updated for a long time, it seems a little deprecated and it does not work with the latest versions of python and vs C++ developing tools. 
I was able to install this package about 2 years ago but now that I'm trying to use it again for a different project, I cannot install it anymore.
Hence an appropriate update on this package will be really appreciated @song940 .
